services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
    environment:
#      - APP_ENV=local
#      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
      - redis
    networks:
      - laravel
    ports:
      - "6001:6001"

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=secret
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/app/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - laravel
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  mariadb_data:

networks:
  laravel:
